// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.3
// source: seckill/v1/seckill.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SeckillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int64                  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ProductID     int64                  `protobuf:"varint,2,opt,name=productID,proto3" json:"productID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeckillRequest) Reset() {
	*x = SeckillRequest{}
	mi := &file_seckill_v1_seckill_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeckillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeckillRequest) ProtoMessage() {}

func (x *SeckillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_v1_seckill_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeckillRequest.ProtoReflect.Descriptor instead.
func (*SeckillRequest) Descriptor() ([]byte, []int) {
	return file_seckill_v1_seckill_proto_rawDescGZIP(), []int{0}
}

func (x *SeckillRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *SeckillRequest) GetProductID() int64 {
	if x != nil {
		return x.ProductID
	}
	return 0
}

type SeckillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderID       int64                  `protobuf:"varint,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
	UserID        int64                  `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	ProductID     int64                  `protobuf:"varint,3,opt,name=productID,proto3" json:"productID,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeckillResponse) Reset() {
	*x = SeckillResponse{}
	mi := &file_seckill_v1_seckill_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeckillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeckillResponse) ProtoMessage() {}

func (x *SeckillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_v1_seckill_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeckillResponse.ProtoReflect.Descriptor instead.
func (*SeckillResponse) Descriptor() ([]byte, []int) {
	return file_seckill_v1_seckill_proto_rawDescGZIP(), []int{1}
}

func (x *SeckillResponse) GetOrderID() int64 {
	if x != nil {
		return x.OrderID
	}
	return 0
}

func (x *SeckillResponse) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *SeckillResponse) GetProductID() int64 {
	if x != nil {
		return x.ProductID
	}
	return 0
}

func (x *SeckillResponse) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_seckill_v1_seckill_proto protoreflect.FileDescriptor

const file_seckill_v1_seckill_proto_rawDesc = "" +
	"\n" +
	"\x18seckill/v1/seckill.proto\x12\n" +
	"seckill.v1\"F\n" +
	"\x0eSeckillRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x03R\x06userID\x12\x1c\n" +
	"\tproductID\x18\x02 \x01(\x03R\tproductID\"w\n" +
	"\x0fSeckillResponse\x12\x18\n" +
	"\aorderID\x18\x01 \x01(\x03R\aorderID\x12\x16\n" +
	"\x06userID\x18\x02 \x01(\x03R\x06userID\x12\x1c\n" +
	"\tproductID\x18\x03 \x01(\x03R\tproductID\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price2T\n" +
	"\x0eSeckillService\x12B\n" +
	"\aSeckill\x12\x1a.seckill.v1.SeckillRequest\x1a\x1b.seckill.v1.SeckillResponseB!Z\x1fproto_definitions/seckill/v1;v1b\x06proto3"

var (
	file_seckill_v1_seckill_proto_rawDescOnce sync.Once
	file_seckill_v1_seckill_proto_rawDescData []byte
)

func file_seckill_v1_seckill_proto_rawDescGZIP() []byte {
	file_seckill_v1_seckill_proto_rawDescOnce.Do(func() {
		file_seckill_v1_seckill_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_seckill_v1_seckill_proto_rawDesc), len(file_seckill_v1_seckill_proto_rawDesc)))
	})
	return file_seckill_v1_seckill_proto_rawDescData
}

var file_seckill_v1_seckill_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_seckill_v1_seckill_proto_goTypes = []any{
	(*SeckillRequest)(nil),  // 0: seckill.v1.SeckillRequest
	(*SeckillResponse)(nil), // 1: seckill.v1.SeckillResponse
}
var file_seckill_v1_seckill_proto_depIdxs = []int32{
	0, // 0: seckill.v1.SeckillService.Seckill:input_type -> seckill.v1.SeckillRequest
	1, // 1: seckill.v1.SeckillService.Seckill:output_type -> seckill.v1.SeckillResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_seckill_v1_seckill_proto_init() }
func file_seckill_v1_seckill_proto_init() {
	if File_seckill_v1_seckill_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_seckill_v1_seckill_proto_rawDesc), len(file_seckill_v1_seckill_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_seckill_v1_seckill_proto_goTypes,
		DependencyIndexes: file_seckill_v1_seckill_proto_depIdxs,
		MessageInfos:      file_seckill_v1_seckill_proto_msgTypes,
	}.Build()
	File_seckill_v1_seckill_proto = out.File
	file_seckill_v1_seckill_proto_goTypes = nil
	file_seckill_v1_seckill_proto_depIdxs = nil
}
