// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gateway/internal/biz"
	"gateway/internal/conf"
	"gateway/internal/data"
	"gateway/internal/server"
	"gateway/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger, registry *conf.Registry) (*kratos.App, func(), error) {
	discovery, err := server.NewEtcdDiscovery(registry)
	if err != nil {
		return nil, nil, err
	}
	userServiceClient, err := data.NewUserClientService(discovery, registry)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(userServiceClient)
	productServiceClient, err := data.NewProductServiceClient(discovery, registry)
	if err != nil {
		return nil, nil, err
	}
	productRepo := data.NewProductRepo(productServiceClient)
	gatewayUsecase := biz.NewGatewayUsecase(userRepo, productRepo)
	gatewayService := service.NewGatewayService(gatewayUsecase)
	grpcServer := server.NewGRPCServer(confServer, gatewayService, logger)
	httpServer := server.NewHTTPServer(confServer, gatewayService, logger)
	registrar, err := server.NewEtcdRegister(registry)
	if err != nil {
		return nil, nil, err
	}
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
	}, nil
}
