// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"seckill_service/internal/biz"
	"seckill_service/internal/conf"
	"seckill_service/internal/data"
	"seckill_service/internal/server"
	"seckill_service/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger, registry *conf.Registry) (*kratos.App, func(), error) {
	discovery, err := server.NewEtcdDiscovery(registry)
	if err != nil {
		return nil, nil, err
	}
	userServiceClient, err := data.NewUserServiceClient(registry, discovery)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(userServiceClient)
	productServiceClient, err := data.NewProductServiceClient(discovery, registry)
	if err != nil {
		return nil, nil, err
	}
	productRepo := data.NewProductRepo(productServiceClient)
	db, err := data.NewGormDB(confData)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(db, logger)
	if err != nil {
		return nil, nil, err
	}
	seckillRepo := data.NewSeckillRepo(dataData)
	seckillUsecase := biz.NewSeckillUsecase(userRepo, productRepo, seckillRepo, registry)
	seckillService := service.NewSeckillService(seckillUsecase)
	grpcServer := server.NewGRPCServer(confServer, seckillService, logger)
	registrar, err := server.NewEtcdRegister(registry)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	app := newApp(logger, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
